Updating Go SDK
chargehound/chargehound-go pull request #21
Opened 2023-03-15 13:35 UTC by pannepu

Updating Go SDK to include additional fields as part of Past Payment section.

### GO SDK Update

Steps followed:

- Clone the [chargehound-go](https://github.com/chargehound/chargehound-go) repository.
- Update the file disputes.go to include the additional fields which are part of this requirement. PR Link.
- Navigate to Chargehound.java file and update the host and protocol as per your local settings.
```
host       = "localhost:3030"
protocol   = "http://"
```

- To test these changes create a new Test class and include the code obtained in the below step.
- Create a new dispute in the local CH test environment and select a template which has past payments section in it. Now obtain the GO sample code by clicking on Submit via API button as shown in the screenshot below, 
![image](https://user-images.githubusercontent.com/120496064/225324323-8182575f-3465-4a47-83f1-8c6e9645d7a8.png)

- Ensure that the newly added fields are included while building the PastPayment object and run the Test file with the command go test
- Check if the dispute is successfully submitted by navigating to the dispute details page. Also ensure that the response contains the newly added fields in the Past Payment section. 
![image](https://user-images.githubusercontent.com/120496064/225324496-013b0f6c-fc72-41af-b962-f28d0c8e3ec3.png)

- Ensure that the disputes are getting submitted successfully even if we don't provide any of the optional fields as part of the Past Payment section.

2023-03-17 11:44 UTC, aggarwalvinay commented
@pannepu: Please update the version of the SDK, changelog, and dispute.go file

2023-03-17 11:45 UTC, aggarwalvinay requested changes
Please update the version of the SDK, changelog, and dispute.go file

2023-03-17 14:06 UTC, aggarwalvinay approved these changes

2023-03-20 17:52 UTC, jagadeeshdeepak-pp approved these changes

2023-03-20 17:53 UTC, jagadeeshdeepak-pp commented
@pannepu TODO: add a test case after we go live.

2023-03-22 03:34 UTC, merged